### PR TITLE
Add agent data capture doc

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
@hypertrace/agent-maintainers could you please review?

**Comment by jcchavezs** [comment]
LGTM, I wonder if this should be in an own folder (e.g. `agent/data-capture`) as I know there is some other documents around agents. The reason why this is important is because we mostly are going to add links to this in code and hence changing it at later stage will be a "breaking change"

**Comment by pavolloffay** [comment]
no objections I can move it there. @davexroth ?

**Comment by pavolloffay** [comment]
@jcchavezs moved

**Review by davexroth — APPROVED** [review]

**Pull request merged**
